export const ASSET_STATUSES = {
  AVAILABLE: "AVAILABLE",
  RESERVED: "RESERVED",
  ASSIGNED: "ASSIGNED",
  IN_USE: "IN_USE",
  RENTED_OUT: "RENTED_OUT",
  SENT_OUT: "SENT_OUT",
  OUTSIDE: "OUTSIDE",
  UNDER_REPAIR: "UNDER_REPAIR",
  SOLD: "SOLD",
  RETIRED: "RETIRED",
  LOST: "LOST",
};

export const ASSET_ACTIONS = {
  ASSIGN_DEVICE: "ASSIGN_DEVICE",
  TRANSFER: "TRANSFER",
  SEND_OUTSIDE: "SEND_OUTSIDE",
  RETURN_DEVICE: "RETURN_DEVICE",
  SEND_FOR_REPAIR: "SEND_FOR_REPAIR",
  RENT_DEVICE: "RENT_DEVICE",
  SELL_DEVICE: "SELL_DEVICE",
  MARK_LOST: "MARK_LOST",
  UNASSIGN_DEVICE: "UNASSIGN_DEVICE",
  COMPLETE_REPAIR: "COMPLETE_REPAIR",
};

export const GENERAL_REASON_OPTIONS = ["OTHER", "PERSONAL_USE", "CLIENT_WORK"];

export const ACTIONS_BY_STATUS = {
  [ASSET_STATUSES.AVAILABLE]: [
    ASSET_ACTIONS.ASSIGN_DEVICE,
    ASSET_ACTIONS.TRANSFER,
    ASSET_ACTIONS.SEND_OUTSIDE,
    ASSET_ACTIONS.SEND_FOR_REPAIR,
    ASSET_ACTIONS.RENT_DEVICE,
    ASSET_ACTIONS.SELL_DEVICE,
    ASSET_ACTIONS.MARK_LOST,
  ],
  [ASSET_STATUSES.ASSIGNED]: [ASSET_ACTIONS.RETURN_DEVICE, ASSET_ACTIONS.MARK_LOST],
  [ASSET_STATUSES.RENTED_OUT]: [ASSET_ACTIONS.RETURN_DEVICE, ASSET_ACTIONS.MARK_LOST],
  [ASSET_STATUSES.SENT_OUT]: [ASSET_ACTIONS.RETURN_DEVICE, ASSET_ACTIONS.MARK_LOST],
  [ASSET_STATUSES.OUTSIDE]: [ASSET_ACTIONS.RETURN_DEVICE, ASSET_ACTIONS.MARK_LOST],
  [ASSET_STATUSES.UNDER_REPAIR]: [ASSET_ACTIONS.RETURN_DEVICE, ASSET_ACTIONS.MARK_LOST],
  [ASSET_STATUSES.SOLD]: [],
  [ASSET_STATUSES.LOST]: [],
};

export function getValidActionsForStatus(status) {
  return ACTIONS_BY_STATUS[status] || [];
}

export function getReasonOptions(action) {
  switch (action) {
    case ASSET_ACTIONS.SEND_FOR_REPAIR:
      return ["REPAIR"];
    case ASSET_ACTIONS.RENT_DEVICE:
      return ["RENTAL"];
    case ASSET_ACTIONS.SELL_DEVICE:
      return ["SALE"];
    case ASSET_ACTIONS.TRANSFER:
      return ["RELOCATION", "STORAGE", "INTERNAL_USE", "OTHER"];
    case ASSET_ACTIONS.RETURN_DEVICE:
      return ["RETURN"];
    default:
      return GENERAL_REASON_OPTIONS;
  }
}

export function getNextStatusForAction(currentStatus, action) {
  switch (action) {
    case ASSET_ACTIONS.ASSIGN_DEVICE:
      return ASSET_STATUSES.ASSIGNED;
    case ASSET_ACTIONS.TRANSFER:
      return currentStatus;
    case ASSET_ACTIONS.SEND_OUTSIDE:
      return ASSET_STATUSES.SENT_OUT;
    case ASSET_ACTIONS.RETURN_DEVICE:
      return ASSET_STATUSES.AVAILABLE;
    case ASSET_ACTIONS.SEND_FOR_REPAIR:
      return ASSET_STATUSES.UNDER_REPAIR;
    case ASSET_ACTIONS.RENT_DEVICE:
      return ASSET_STATUSES.RENTED_OUT;
    case ASSET_ACTIONS.SELL_DEVICE:
      return ASSET_STATUSES.SOLD;
    case ASSET_ACTIONS.MARK_LOST:
      return ASSET_STATUSES.LOST;
    default:
      return currentStatus;
  }
}
