export const ASSET_STATUSES = {
  AVAILABLE: "AVAILABLE",
  RESERVED: "RESERVED",
  ASSIGNED: "ASSIGNED",
  IN_USE: "IN_USE",
  OUTSIDE: "OUTSIDE",
  UNDER_REPAIR: "UNDER_REPAIR",
  SOLD: "SOLD",
  RETIRED: "RETIRED",
  LOST: "LOST",
};

export const ASSET_ACTIONS = {
  ASSIGN_DEVICE: "ASSIGN_DEVICE",
  UNASSIGN_DEVICE: "UNASSIGN_DEVICE",
  SEND_OUTSIDE: "SEND_OUTSIDE",
  RETURN_DEVICE: "RETURN_DEVICE",
  SEND_FOR_REPAIR: "SEND_FOR_REPAIR",
  COMPLETE_REPAIR: "COMPLETE_REPAIR",
  SELL_DEVICE: "SELL_DEVICE",
  MARK_LOST: "MARK_LOST",
};

export const GENERAL_REASON_OPTIONS = [
  "OTHER",
  "REPAIR",
  "RETURN",
  "TRANSFER",
  "PERSONAL_USE",
  "CLIENT_WORK",
];

export const OUTSIDE_REASON_OPTIONS = ["RENTAL", "SALE", "WFH", "VENDOR"];

export const ACTIONS_BY_STATUS = {
  [ASSET_STATUSES.AVAILABLE]: [
    ASSET_ACTIONS.ASSIGN_DEVICE,
    ASSET_ACTIONS.SEND_OUTSIDE,
    ASSET_ACTIONS.SEND_FOR_REPAIR,
    ASSET_ACTIONS.MARK_LOST,
  ],
  [ASSET_STATUSES.ASSIGNED]: [
    ASSET_ACTIONS.UNASSIGN_DEVICE,
    ASSET_ACTIONS.SEND_OUTSIDE,
    ASSET_ACTIONS.MARK_LOST,
  ],
  [ASSET_STATUSES.OUTSIDE]: [
    ASSET_ACTIONS.RETURN_DEVICE,
    ASSET_ACTIONS.SELL_DEVICE,
    ASSET_ACTIONS.MARK_LOST,
  ],
  [ASSET_STATUSES.UNDER_REPAIR]: [
    ASSET_ACTIONS.COMPLETE_REPAIR,
    ASSET_ACTIONS.MARK_LOST,
  ],
};

export function getValidActionsForStatus(status) {
  return ACTIONS_BY_STATUS[status] || [];
}

export function getReasonOptions(action, status) {
  if (action === ASSET_ACTIONS.SEND_OUTSIDE && status === ASSET_STATUSES.AVAILABLE) {
    return OUTSIDE_REASON_OPTIONS;
  }

  return GENERAL_REASON_OPTIONS;
}
